# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b68a90c4f6a1314df27acfe3061f2a1"
name = "app-billing"
handle = "app-billing-1"
application_url = "https://organized-combining-projector-iraq.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-rakesh.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://organized-combining-projector-iraq.trycloudflare.com/auth/callback",
  "https://organized-combining-projector-iraq.trycloudflare.com/auth/shopify/callback",
  "https://organized-combining-projector-iraq.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
